### ISSUE TITLE
Question about need for error profile learning for each sample 

### ISSUE THREAD

**Issue by aistBMRG** [DormanLab/AmpliCI#1]
Hi,

Thanks for developing this new tool; seems very good and worked well in my initial testing.

Just a small question, should the error learning step be performed for each sample? Or can we use of subset of samples and then use that profile for all other samples processing and sequencing simultaneously. As you know, this is the approach of dada2 and should speed up the analyses.

Thanks for any insights.

Dieter

**Comment by kdorman** [comment]
Hi Dieter,

Indeed such a procedure of estimation on a subset of samples should speed up analyses, and you have to do what you have to do about speed. Error profiles should be similar for multiple, similar samples run on the same platform around the same time, so it is also probably a good way to speed it up. There are other concerns with error estimation, such as whether it converged too soon, before major clusters had been separated. We've tuned it to work well in a number of test cases, but let us know if it misbehaves in your hands.

Karin

**Comment by jianshu93** [comment]
run multiple samples separately or pool all samples? Will the variants inferred for each sample used to define singleton for other samples?

Thanks,

Jianshu
