### ISSUE TITLE
pool samples or run one by one and how does it deal with low abundance sequences.e.g. singletons

### ISSUE THREAD

**Issue by jianshu93** [DormanLab/AmpliCI#2]
Dear Xiyu and Karin,

I am comparing it with dada2 and unoise3 for very large dataset (1000 samples). I am wondering whether I should pool all samples or just run them one by one. What reads merging software do you recommend, PEAR, search --fastq_mergepairs or NGmerge? How does it deal with singletons that exists in each samples?

Thanks,

Jianshu

**Comment by xiyupeng** [comment]
Hi, Jianshu,

For AmpliCI, I would recommend to run them one by one. Error profiles can be estimated from each sample and be used to infer variants from each sample. A simple shell script could help you to do this quickly. For very large datasets, pooling samples together would significantly increase the computation complexity (especially for memory). Hopefully we would come up a more scalable method in the future.

AmpliCI clusters sequences heavily based on the quality score. I would recommend merges that could provide good estimates of quality score. NGmerge uses empirical quality score update based on control phage data that is included in many runs. We suspect that NGmerge will produce the most accurate results. if search --fastq_mergepairs is referring to the read pair merger in USEARCH, you can also use it. These quality scores are updated by math and NGmerge authors say the result is similar to USEARCH.

Unfortunately, we currently do not support to detect singletons in our model. The default abundance threshold of AmpliCI is 2. You can change the abundance threshold to any real number > 1. Considering singletons will lead to a large amount of false positives in real data in practice. It is really difficult to distinguish between real singletons and singleton errors. As far as I know, though DADA2 and Unoise could infer singletons with additional options, they do not recommend to use it unless you have very low depth samples.

Best,
Xiyu

**Comment by jianshu93** [comment]
Hello Xiyu，Thanks for quick response. I got the whole idea now. I am comparing it with all popular asv algorithms for complex dataset like soil. I am a bioinfomatic student at georgia tech and I am very interested in amplicon analysis. Would it be possible that we can know each other more(my WeChat account is JansueChao)

Thank you,

Jianshu

________________________________

**Comment by kdorman** [comment]
Hi Jianshu,

I am the source of information about paired read merging in Xiyu's response (she knows all about the best ways to run AmpliCI), and I just need to add that the NGmerge publication actually finds USEARCH merging (and PEAR) to greatly overestimate the confidence in base calls when both reads agree with high quality base calls, so NGmerge and USEARCH may _not_ produce similar results. PEAR and USEARCH produce similar results, according to the NGmerge publication.

Good luck with  your study! There are differences between the ASV detection methods, and figuring out which is more correct is an important, but challenging task. We'll be interested to know what you find.

Best,
Karin
