### ISSUE TITLE
Perhaps not suitable for pair-end reads?

### ISSUE THREAD

**Issue by billzt** [DormanLab/AmpliCI#5]
AmpliCI requires reads in equal lengths.

After Pair-end reads are merged, it is impossible to keep the merged result in the same length.

If we use other tools to trim merged reads into the same length, a lot of information would be lost.

**Comment by xiyupeng** [comment]
We are currently working on a new version for datasets with variable read lengths, especially for the fungal ITS data.

If the range of reads' lengths is low, you can ignore the warning and run AmpliCI, though the error rates need to be learned from a subset of reads with same length. We have tested this and have no problem with it. But if the range is high, a lot needs to be considered, e.x. parameters for NW alignment.

**Comment by billzt** [comment]
Thank you.

By the way, in your publication, multiple tools have been compared, which I noticed that AmpliCI and unoise3 are almost the best ones. However unoise3 is much easier to install and can accept variable length. AmpliCI is too difficult to install.

**Comment by xiyupeng** [comment]
Though the prerequisites are long, most times, you just need to preinstall CMake (then it will automatically locate all required libraries on your computer if you have installed R). Though we do not provide binaries for all platforms as USEARCH did, the source codes are provided and have been tested across multiple platforms, which we think is more convenient for users.

**Comment by billzt** [comment]
> Though the prerequisites are long, most times, you just need to preinstall CMake (then it will automatically locate all required libraries on your computer if you have installed R). Though we do not provide binaries for all platforms as USEARCH did, the source codes are provided and have been tested across multiple platforms, which we think is more convenient for users.

However the required version of gcc and cmake is too high for common lab servers (usually centos 7). New develop environment have to be set. Providing a binary might be a good idea.

**Comment by xiyupeng** [comment]
Thank you. Glad to know that. I will test if it could be compiled with the older versions of Cmake and gcc.
